# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      
env:
  GPC_PROJECT_ID: rholcombe-gke-test
  RUN_REGION: us-central1
  SERVICE_NAME: bingo-creator
  NODE_VERSION: 16.13.1

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: ${NODE_VERSION}

      - run: yarn install

      - run: yarn test -- --watchAll=false

  deploy:
    name: Deploy to Cloud Run
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${SERVICE_NAME}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
            
      - run: echo ${{ steps.docker_build.outputs.digest }}
